### ISSUE TITLE
Add support to the repository of IPTV

### ISSUE THREAD

**Issue by GrimPixel** [aldrinzigmundv/digilogtv#1]
There are a lot of channels:
https://github.com/iptv-org/iptv

**Comment by aldrinzigmundv** [comment]
I specifically chose [Free-TV/IPTV](https://github.com/Free-TV/IPTV) because Linux Mint decided to make it the default provider for [Hypnotix](https://github.com/linuxmint/hypnotix), instead of [IPTV-ORG/IPTV](https://github.com/iptv-org/iptv), even though the latter is larger. Linux Mint stated that Free-TV/IPTV was the only provider meeting their criteria of offering free, legal, publicly available content. This aligns with my own criteria for maintaining the app on major app stores.

I believe I have personally examined both providers and found that neither is well-maintained. This prompted my decision to stick with English news channels, which I frequently watch, in order to ensure a better user experience and avoid the inconvenience of dealing with non-working channels.

At the moment, it's technically possible to add channels by forking and building the app yourself (at lib/services/channels.dart). Additionally, I do have plans to develop a separate IPTV client app, which will provide more options and flexibility in the future.

Feel free to respond if you have anymore suggestions or questions.

**Comment by GrimPixel** [comment]
I see. That guy has quite some principles. He could add a line “Only channels from member countries in the United Nations”.
Anyhow, thank you for answering it. Hope your new feature goes smoothly.

**Comment by aldrinzigmundv** [comment]
Are you referring to [Free-TV/IPTV](https://github.com/Free-TV/IPTV)? Do you think any channels were excluded solely because their countries are not part of the United Nations? If you have any channels in mind, please share, and I'll take some of my time to look at it. Thanks.

**Comment by aldrinzigmundv** [comment]
Please create a new issue if you have any further questions or suggestions. I am closing this issue due to lack of response. Thank you.
